kind: pipeline
name: default

steps:

  - name: compile
    image: node
    commands:
      - npm install
      - ./node_modules/typescript/bin/tsc

  - name: aws-cdk
    image: eignhpants/docker-aws-cdk
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: sheeta_aws_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: sheeta_aws_secret
    commands:
    - cdk synth
